#
# Message from CarMaker ROS Node to external ROS Node
#

# General
std_msgs/Header  header                                 # General ROS Header (optional)
builtin_interfaces/Time    time                                   # ROS time when message was sent (optional)
int64   cycleno                                # Cycle number since simulation start (optional)
float64 synthdelay                             # Synthetic delay to check synchronization (optional)


float64  roll
float64  pitch
float64  yaw

float64  vx
float64  vy
float64  vz
float64  roll_vel
float64  pitch_vel
float64  yaw_vel

float64  ax
float64  ay
float64  az
float64  roll_acc
float64  pitch_acc
float64  yaw_acc
